Feat - Voting Power
CreamFi/cream-voting-power pull request #1
Opened 2021-04-22 01:30 UTC by akyo8

2021-04-22 02:42 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +    uint256 public MINIMUM_VOTING_POWER = 1;
should be 1e18

2021-04-22 02:42 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +    function getVotingPower(address _holder) public view returns (uint256) {
We'll like to conform the standard ERC20 interface for this function signature
`balanceOf`

2021-04-22 02:42 UTC, jeremyHD commented on scripts/sample-script.js
> +      console.log(`=========${addresses[i]}=========\n${response}`);
Oh nice, you have written the test that I was trying to tell you about! Sorry I didn't see this just now

2021-04-22 02:46 UTC, jeremyHD commented on scripts/example.json
> +  "0xa805cb6907130c0c7F3534Ee2EBc62D806FFB820"
And you also bring the same addresses from the examples.

If you set the `periods` in [example.json](https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/cream/examples.json#L15) for snapshot strategy.
And run `npm run test --strategy=cream` on snapshot.js repo, the result should be the same or close enough

2021-04-22 02:48 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +        uint256 totalLending = ICToken(crCream).balanceOf(_holder) * ICToken(crCream).exchangeRateStored() / 1e18;
```suggestion
        uint256 totalLending = ICToken(crCream).balanceOf(_holder) * ICToken(crCream).exchangeRateStored().div( 1e18);
```

2021-04-22 02:49 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +        );
return 0 if votingPower < Min voting power

2021-04-23 01:46 UTC, akyo8 commented on scripts/example.json
> +  "0xa805cb6907130c0c7F3534Ee2EBc62D806FFB820"
@jeremyHD 
When `periods` was set `0`, it ran into this issue `Error: division by zero`.
Please tell me if you have any idea with it. Thanks

2021-04-23 02:12 UTC, jeremyHD commented on scripts/example.json
> +  "0xa805cb6907130c0c7F3534Ee2EBc62D806FFB820"
set to 1. My bad

2021-04-23 02:41 UTC, akyo8 commented
@jeremyHD 
I updated with fixing of above comments and added defiPulse amount.
If you have any improvements or suggestions, please let me know. thanks

2021-04-23 02:59 UTC, jeremyHD requested changes

2021-04-23 02:59 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +    address public constant defiPulse = 0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b;
should be defiPulseIndex or just name it dpi

2021-04-23 02:59 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +
Please add a sanity check here
```
if (borrowed > totalLending) {
    return 0
}
```

or else safeMath will revert if underflow

2021-04-23 02:59 UTC, jeremyHD commented on contracts/CreamVotingPower.sol
> +            totalStaked.add(ILPool(lPool[i]).balanceOf(_holder));
```suggestion
            totalStaked = totalStaked.add(ILPool(lPool[i]).balanceOf(_holder));
```

2021-04-23 03:26 UTC, akyo8 commented on contracts/CreamVotingPower.sol
> +            totalStaked.add(ILPool(lPool[i]).balanceOf(_holder));
fixed

2021-04-23 03:26 UTC, akyo8 commented on contracts/CreamVotingPower.sol
> +
added sanity check for it

2021-04-23 03:27 UTC, akyo8 commented on contracts/CreamVotingPower.sol
> +    address public constant defiPulse = 0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b;
it's been named defiPulseIndex

2021-04-23 03:28 UTC, akyo8 commented
@jeremyHD 
Please check above fixing and this is final results of testing
`
=========0xeB8A4eADd643Ea3873dfecFBa18BD709D3206919=========
25988067596870823513528
=========0xe0Ba6c4c82376c76386D1Ca2ae2516Ab18882e3C=========
443299961957519273343
=========0xE32F576578F9aea942226B6A280fbCe93da45638=========
0
=========0x56e0150b3cbb9f191fe360740fcfa2edbd1b3697=========
83128575877236447792
=========0xbbe21151c726F9EEc42516524f58D0057261CC8a=========
0
=========0x6bD48938B9F9Dd02ee3D6dccd0379DDF0af22D38=========
51222026950618754185
=========0xa805cb6907130c0c7F3534Ee2EBc62D806FFB820=========
0
`

2021-04-23 03:37 UTC, jeremyHD approved these changes

2021-04-23 03:38 UTC, merged